### ISSUE TITLE
Indexing rate

### ISSUE THREAD

**Issue by Ivshti** [kevinlynx/dhtcrawler2#3]
Hello,
This is not really a bug/issue, but there it goes:
What can be done to increase the torrent indexing rate? I am running the latest version of the crawler for 8 hours now and it has only indexed 380 torrents.
The machine is pretty good with a 40 Mbps network connection.
Anything I can do to improve the indexing rate?

**Comment by kevinlynx** [comment]
Your rate is not normal. Try keep dht_state directory, the crawler will save dht nodes to that directory, that will make the crawler received lots of queries. Show me your stats.

**Comment by Ivshti** [comment]
As of today (it's has been running since 6AM GMT+2 on 14th of July) 

```
total 380 torrents

2013-07-15 RecvQuery 0 ProcessedQuery 0 Updated 0 New 0
2013-07-14 RecvQuery 1500 ProcessedQuery 709 Updated 189 New 501
2013-07-13 RecvQuery 0 ProcessedQuery 0 Updated 0 New 0
```

**Comment by kevinlynx** [comment]
too slow... `RecvQuery` indicates query count the crawler has been received from DHT network. 50 DHT nodes can collect 1,000,000 query count more or less in 24 hours, 1500 queries can be reached in several minutes. DHT queries are sent by UDP packets, the other nodes will use your IP address to sent the packet, maybe there're packets blocked by some firewalls or routers, I'm not sure.

**Comment by Ivshti** [comment]
I have a VPS with a 40 Mbps connection, unique IP and a disabled firewall. My theory is that SELinux is blocking something, so I'll do a few tries with VPSes with other hosting companies, other operating systems and report back the result.

**Comment by Ivshti** [comment]
Okay, I tried a new VPS, without SELinux, here's the result

```
total 0 torrents

2013-07-17 RecvQuery 24690 ProcessedQuery 0 Updated 0 New 0
2013-07-16 RecvQuery 0 ProcessedQuery 0 Updated 0 New 0
2013-07-15 RecvQuery 0 ProcessedQuery 0 Updated 0 New 0
```

Now processing the torrents does not appear to be working, although it crawled 25 000 torrents for two hours.

**Comment by kevinlynx** [comment]
yes, looks like a bit normal now

BTW, i'm currently working on this project, so there must some bugs there, i deploy the crawler at bt.cm

**Comment by Ivshti** [comment]
bt.cm is great! Good work, keep it up!

Anyway, are you deploying it on your own server? What OS/setup are you using?

I resolved the issue with not indexing any torrents - it was related to MongoDB (running it on OpenVZ on a 32 bit system).

**Comment by kevinlynx** [comment]
it's my friend's server.
Windows 2008 64bit (and now i suggest deploy on linux because of mongodb)
crawler 150 nodes, hash_reader 4, 
dht_crawler.config
   {hash_max_cache,1000},  % crawler will cache max 1000 hashes in memory before write to db,
   {cache_max_time,300},  % max hash cache keep time
